version: "3.3"

services:
  web:
    container_name: entro-client
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Required to sync file changes.
      - .:/usr/src/app
      # Required to not break node modules.
      - /usr/src/app/node_modules
      # Required for next to do it's thing.
      - /usr/src/app/.next
    env_file:
      - .env.local
    ports:
      - 3000:3000
    command: npm run dev